import type { MethodName, EventName } from './ipc';

/** The whitelist the preload exposes; must list every key of `Methods`. */
export const METHODS = [
  'task.revertMerge',
  'window.minimize',
  'window.toggleMaximize',
  'window.close',
  'window.isMaximized',
  'app.getLocale',
  'app.setLocale',
  'app.getSetting',
  'app.setSetting',
  'app.projectDefaults',
  'app.setProjectDefaults',
  'app.version',
  'diagnostics.export',
  'app.checkUpdate',
  'updates.state',
  'updates.download',
  'updates.apply',
  'app.pickApp',
  'projects.list',
  'projects.pickFolder',
  'projects.inspect',
  'projects.defaultParent',
  'projects.add',
  'projects.create',
  'projects.remove',
  'projects.overview',
  'projects.relocate',
  'projects.openIn',
  'project.rename',
  'project.pickLogo',
  'project.removeLogo',
  'project.settings',
  'project.saveSettings',
  'project.hasCode',
  'import.scan',
  'import.start',
  'import.review',
  'import.openSource',
  'tabs.get',
  'tabs.set',
  'agents.list',
  'agents.refresh',
  'agents.install',
  'agents.login',
  'agents.models',
  'agents.commands',
  'agents.config',
  'agents.openConfigDir',
  'tasks.list',
  'tasks.slots',
  'tasks.run',
  'tasks.archive',
  'tasks.delete',
  'tasks.move',
  'tasks.unblock',
  'tasks.cancel',
  'tasks.merge',
  'tasks.assign',
  'plan.milestones',
  'plan.create',
  'plan.update',
  'plan.delete',
  'plan.reorder',
  'plan.placeTask',
  'docs.list',
  'docs.read',
  'docs.write',
  'docs.create',
  'docs.createSpec',
  'docs.setAdrStatus',
  'docs.setSpecStatus',
  'docs.reveal',
  'task.open',
  'task.send',
  'task.respond',
  'task.interrupt',
  'task.stopBackground',
  'task.setSettings',
  'task.merge',
  'task.toggleCriterion',
  'chats.list',
  'chats.defaults',
  'chat.open',
  'chat.create',
  'chat.send',
  'chat.respond',
  'chat.interrupt',
  'chat.setSettings',
  'chat.archive',
  'chat.proposal',
  'files.suggest',
  'files.exist',
  'files.open',
  'files.diff',
  'files.pick',
  'shell.openExternal',
] as const satisfies readonly MethodName[];

export const EVENTS = [
  'updates.changed',
  'window.maximized',
  'agents.changed',
  'project.changed',
  'task.events',
  'task.changed',
  'chat.events',
  'chats.changed',
  'import.progress',
] as const satisfies readonly EventName[];

// Compile-time check that METHODS covers every method.
type Missing = Exclude<MethodName, (typeof METHODS)[number]>;
const _complete: Missing extends never ? true : Missing = true;
void _complete;
